name: bob
version: 1.4.0.10

dependencies:
  - base

library:
  exposed-modules: Bob
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - text

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bob
      - hspec
